In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

Logistic Regression

In [4]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9611111111111111

SVM

In [9]:
#svm = SVC(gamma='auto')
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.987037037037037

Random Forest

In [11]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9685185185185186

K FOLD CROSS-VALIDATION

Basic Example

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [14]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


Use KFold for Digits example.

In [15]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [29]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
scores_logistic=[]
scores_svc=[]
scores_rf=[]
for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],\
                                    digits.target[train_index],digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train,X_test,y_train,y_test))
    scores_svc.append(get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [30]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [31]:
scores_svc

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [32]:
scores_rf

[0.9232053422370617, 0.9465776293823038, 0.9282136894824707]

CROSS_VAL_SCORE_FUNCTION
#above we have done the deep implementation of kfold validation.

In [33]:
#Here we directly use the cross_val function to do kfold validation

In [34]:
from sklearn.model_selection import cross_val_score

Logistic Regression Model Performance using cross_val_score

In [37]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

SVC MOdel Performance using cross_val_score

In [41]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

Random Forest Classifier Performance using cross_val_score

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)

array([0.93322204, 0.94490818, 0.92320534])

In [45]:
#cross_val_score uses stratifiedKFold by default.

PARAMETER TUNING USING KFOLD CROSS VALIDAITON \
We compared different models above,now we use cross_val_score for parameter tuning of a particular model.

In [47]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target,cv=10)
np.average(scores1)

0.880350713842334

In [48]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target,cv=10)
np.average(scores2)

0.9454686530105523

In [49]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target,cv=10)
np.average(scores3)

0.941024208566108

In [50]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=10)
np.average(scores4)

0.9460180012414648

Here we used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.